workflows:
  ios-workflow:
    name: ios-workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      ios_signing:
          distribution_type: app_store
          bundle_identifier: com.example.apppreview
      vars:
        XCODE_SCHEME: "Runner"
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Run Flutter pub get
        script: |
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build unsigned .app
        script: |
          xcodebuild -workspace "ios/Runner.xcworkspace" \
            -scheme "Runner" \
            -configuration "Debug" \
            -sdk iphonesimulator \
            -derivedDataPath ios/output
    artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app  