workflows:
  ios-workflow:
    name: ios-workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Run Flutter pub get
        script: |
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build the .app
        script: | 
            xcodebuild build \
              -workspace "Runner" \
              -scheme "$XCODE_SCHEME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
              -configuration Debug \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/Runner.app  